import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["error", "warn", "info", "debug"]>>;
    PORT: z.ZodOptional<z.ZodPipeline<z.ZodEffects<z.ZodString, number, string>, z.ZodNumber>>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    POSTGRES_HOST: z.ZodDefault<z.ZodString>;
    POSTGRES_PORT: z.ZodDefault<z.ZodPipeline<z.ZodEffects<z.ZodString, number, string>, z.ZodNumber>>;
    POSTGRES_USER: z.ZodDefault<z.ZodString>;
    POSTGRES_PASSWORD: z.ZodDefault<z.ZodString>;
    POSTGRES_DB: z.ZodOptional<z.ZodString>;
    RABBITMQ_URL: z.ZodOptional<z.ZodString>;
    RABBITMQ_HOST: z.ZodDefault<z.ZodString>;
    RABBITMQ_PORT: z.ZodDefault<z.ZodPipeline<z.ZodEffects<z.ZodString, number, string>, z.ZodNumber>>;
    RABBITMQ_USER: z.ZodDefault<z.ZodString>;
    RABBITMQ_PASSWORD: z.ZodDefault<z.ZodString>;
    REDIS_URL: z.ZodOptional<z.ZodString>;
    REDIS_HOST: z.ZodDefault<z.ZodString>;
    REDIS_PORT: z.ZodDefault<z.ZodPipeline<z.ZodEffects<z.ZodString, number, string>, z.ZodNumber>>;
    REDIS_PASSWORD: z.ZodOptional<z.ZodString>;
    SERVICE_NAME: z.ZodOptional<z.ZodString>;
    JWT_SECRET: z.ZodOptional<z.ZodString>;
    JWT_ACCESS_TOKEN_EXPIRY: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    REFRESH_TOKEN_EXPIRY: z.ZodOptional<z.ZodDefault<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test";
    LOG_LEVEL: "error" | "warn" | "info" | "debug";
    POSTGRES_HOST: string;
    POSTGRES_PORT: number;
    POSTGRES_USER: string;
    POSTGRES_PASSWORD: string;
    RABBITMQ_HOST: string;
    RABBITMQ_PORT: number;
    RABBITMQ_USER: string;
    RABBITMQ_PASSWORD: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    PORT?: number | undefined;
    DATABASE_URL?: string | undefined;
    POSTGRES_DB?: string | undefined;
    RABBITMQ_URL?: string | undefined;
    REDIS_URL?: string | undefined;
    REDIS_PASSWORD?: string | undefined;
    SERVICE_NAME?: string | undefined;
    JWT_SECRET?: string | undefined;
    JWT_ACCESS_TOKEN_EXPIRY?: string | undefined;
    REFRESH_TOKEN_EXPIRY?: string | undefined;
}, {
    NODE_ENV?: "development" | "production" | "test" | undefined;
    LOG_LEVEL?: "error" | "warn" | "info" | "debug" | undefined;
    PORT?: string | undefined;
    DATABASE_URL?: string | undefined;
    POSTGRES_HOST?: string | undefined;
    POSTGRES_PORT?: string | undefined;
    POSTGRES_USER?: string | undefined;
    POSTGRES_PASSWORD?: string | undefined;
    POSTGRES_DB?: string | undefined;
    RABBITMQ_URL?: string | undefined;
    RABBITMQ_HOST?: string | undefined;
    RABBITMQ_PORT?: string | undefined;
    RABBITMQ_USER?: string | undefined;
    RABBITMQ_PASSWORD?: string | undefined;
    REDIS_URL?: string | undefined;
    REDIS_HOST?: string | undefined;
    REDIS_PORT?: string | undefined;
    REDIS_PASSWORD?: string | undefined;
    SERVICE_NAME?: string | undefined;
    JWT_SECRET?: string | undefined;
    JWT_ACCESS_TOKEN_EXPIRY?: string | undefined;
    REFRESH_TOKEN_EXPIRY?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare function getEnv(): Env;
export declare function validateEnv(): void;
export {};
//# sourceMappingURL=index.d.ts.map